### ISSUE TITLE
Out of range on column 'heap_xxx'

### ISSUE THREAD

**Issue by AvailCat** [X-Profiler/xtransit-manager#2]
Hello,

https://github.com/X-Profiler/xtransit-manager/blob/0b5cc62648b332a32daf5980a4d9c8883328580b/db/init.sql#L22

The max value of INT type was too small for such data, it should use BIGINT. In my case, heap_available is `8535654496` and the max of INT was only `2147483647`.

**Comment by hyj1991** [comment]
It seems that you have setted the flag `max-olfd-space-size`, I'll fix it :)

**Comment by hyj1991** [comment]
landed in b84e169a6253af5301b43e3c0bc7aa2b07ffa217.
