### ISSUE TITLE
redis use cluster 

### ISSUE THREAD

**Issue by minggangLu** [X-Profiler/xtransit-manager#6]
we use redis cluster config online deploy,find that the data will delete  itself,is it supports egg-redis cluster

**Comment by hyj1991** [comment]
> https://github.com/X-Profiler/xtransit-manager/blob/master/config/plugin.js#L15

**Comment by minggangLu** [comment]
we have an egg project and use egg-xtransit to connect to the websocket,the connection will terminate after a few minites，and the logs only have 'websocket client connecting to xxx' , doesn't have ' websocket client has been connected.' ,is it not connect to the ws
